(function(){
"use strict";
const C=window.__OMNI_CORE,UX=window.OmniUX;if(!C||!UX)return;
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
const en=()=>C.lang==="en",esc=C.esc;
const INTENTS={maintain:["유지하고 싶어요","Maintain it"],complete:["완료하고 싶어요","Complete it"]};
const AREA_LABEL={body:["몸","Body"],mind:["마음","Mind"],learn:["배움","Learning"],work:["일","Work"],money:["돈","Money"],relation:["관계","Relationships"],home:["살림","Home"],play:["놀이","Play"]};
const maintain={
body:{ko:"수면 균형",en:"Sleep balance",measure:{input:"duration",aggregation:"average",success:"range",period:"day",source:"manual",unit:"시간"},reasonKo:"수면은 횟수보다 실제 시간과 개인이 정한 범위가 중요해요.",reasonEn:"Actual sleep duration and your own range matter more than occurrence count."},
mind:{ko:"기분 균형",en:"Mood balance",measure:{input:"rating",aggregation:"average",success:"none",period:"day",source:"manual",unit:"점",scaleMin:1,scaleMax:5},reasonKo:"기분은 성공·실패로 단정하지 않고 점수의 흐름을 살펴봐요.",reasonEn:"Track the pattern without labeling a mood score as success or failure."},
learn:{ko:"학습 집중도",en:"Learning focus",measure:{input:"rating",aggregation:"average",success:"range",period:"week",source:"manual",unit:"점",scaleMin:1,scaleMax:5},reasonKo:"공부 횟수보다 스스로 느낀 집중도의 평균과 범위를 살펴봐요.",reasonEn:"Review your focus ratings rather than merely counting study sessions."},
work:{ko:"업무량 균형",en:"Workload balance",measure:{input:"rating",aggregation:"average",success:"range",period:"week",source:"manual",unit:"점",scaleMin:1,scaleMax:5},reasonKo:"업무량을 단순 합계로 평가하지 않고 직접 정한 범위와 비교해요.",reasonEn:"Compare workload ratings with your own range rather than a universal target."},
money:{ko:"월 생활비 범위",en:"Monthly spending range",measure:{input:"amount",aggregation:"sum",success:"range",period:"month",source:"manual",unit:"원"},reasonKo:"생활비는 월 합계를 사용자가 정한 최소·최대 범위와 비교해요.",reasonEn:"Compare monthly total spending with the range you set."},
relation:{ko:"관계 만족도",en:"Relationship check-in",measure:{input:"rating",aggregation:"average",success:"none",period:"week",source:"manual",unit:"점",scaleMin:1,scaleMax:5},reasonKo:"관계를 좋고 나쁨으로 판정하지 않고 정기적인 느낌의 흐름을 봐요.",reasonEn:"Observe the pattern without judging the relationship as good or bad."},
home:{ko:"집안 상태",en:"Home check-in",measure:{input:"rating",aggregation:"latest",success:"range",period:"week",source:"manual",unit:"점",scaleMin:1,scaleMax:5},reasonKo:"집안 상태는 최근 점수와 내가 정한 편안한 범위를 비교해요.",reasonEn:"Compare the latest home rating with your own comfortable range."},
play:{ko:"여가 시간 균형",en:"Leisure balance",measure:{input:"duration",aggregation:"sum",success:"range",period:"week",source:"manual",unit:"시간"},reasonKo:"여가는 많을수록 좋다고 단정하지 않고 주간 시간 범위를 직접 정해요.",reasonEn:"Use your own weekly time range instead of assuming more is always better."}
};
const complete={
body:["건강검진 준비","Health check preparation"],mind:["상담 준비","Counseling preparation"],learn:["강의 완료","Course completion"],work:["프로젝트 완료","Project completion"],money:["빚 상환 계획","Debt payoff plan"],relation:["가족 행사 준비","Family event preparation"],home:["이사 준비","Moving preparation"],play:["여행 준비","Trip preparation"]
};
let alphaIntent=null,alphaArea="body",currentDraft=null,currentReason="";

function clone(x){return JSON.parse(JSON.stringify(x));}
function milestoneSeed(area){const n=complete[area]||complete.work;return {area,intent:"complete",name:en()?n[1]:n[0],type:"count",goal:0,cycle:"total",unit:"단계",step:1,reason:en()?"Break the finish line into checkable steps and keep the deadline visible.":"완료 기준을 확인 가능한 단계로 나누고 마감일까지 남은 시간을 함께 봐요.",measure:{input:"milestone",aggregation:"completion",success:"deadline",period:"deadline",source:"manual",unit:"단계",milestones:[{id:"m1",label:en()?"First step":"첫 단계"},{id:"m2",label:en()?"Second step":"두 번째 단계"}]}};}
function alphaSeeds(intent,area){if(intent==="maintain"){const x=maintain[area]||maintain.body;return [{area,intent,name:en()?x.en:x.ko,type:"count",goal:0,cycle:x.measure.period==="week"?"week":x.measure.period==="month"?"month":"day",unit:x.measure.unit,step:1,reason:en()?x.reasonEn:x.reasonKo,measure:clone(x.measure)}];}return [milestoneSeed(area)];}
function contractLabel(m){if(!m)return en()?"Needs confirmation":"기준 확인 필요";const input=en()?{count:"Count",amount:"Amount",duration:"Duration",check:"Check",elapsed:"Elapsed",snapshot:"Snapshot",rating:"Rating",milestone:"Milestone"}:{count:"횟수",amount:"양",duration:"시간",check:"체크",elapsed:"경과",snapshot:"현재값",rating:"점수",milestone:"단계"},agg=en()?{sum:"Sum",count:"Occurrences",latest:"Latest",average:"Average",rate:"Rate",streak:"Streak",elapsed:"Elapsed",completion:"Completion"}:{sum:"합계",count:"발생",latest:"최신값",average:"평균",rate:"비율",streak:"연속",elapsed:"경과",completion:"완료율"},period=en()?{event:"Each time",day:"Daily",week:"Weekly",month:"Monthly",rolling:"Rolling",total:"All time",deadline:"Deadline"}:{event:"매회",day:"하루",week:"주",month:"월",rolling:"최근 기간",total:"전체",deadline:"마감일"};return (input[m.input]||m.input)+" · "+(agg[m.aggregation]||m.aggregation)+" · "+(period[m.period]||m.period);}
function ensureIntentButtons(){const entry=$("#entryIntents");if(entry)Object.keys(INTENTS).forEach(k=>{if(!entry.querySelector('[data-alpha-intent="'+k+'"]')){const b=document.createElement("button");b.dataset.alphaIntent=k;b.textContent=INTENTS[k][en()?1:0];entry.appendChild(b);}});const edit=$("#edIntentSeg");if(edit)Object.keys(INTENTS).forEach(k=>{if(!edit.querySelector('[data-alpha-edit-intent="'+k+'"]')){const b=document.createElement("button");b.type="button";b.dataset.alphaEditIntent=k;b.textContent=INTENTS[k][en()?1:0].replace(en()?" it":"하고 싶어요","");edit.appendChild(b);}});}
function renderAlphaResults(){const box=$("#entryResults"),title=$("#entryResultTitle");if(!box||!alphaIntent)return;ensureIntentButtons();$$("#entryIntents button").forEach(b=>b.classList.toggle("on",b.dataset.alphaIntent===alphaIntent));$$("#entryAreas button").forEach(b=>b.classList.toggle("on",b.dataset.area===alphaArea));const list=alphaSeeds(alphaIntent,alphaArea);if(title)title.textContent=(AREA_LABEL[alphaArea]||AREA_LABEL.body)[en()?1:0]+" · "+INTENTS[alphaIntent][en()?1:0];box.innerHTML=list.map(s=>'<button class="entry-seed" data-alpha-seed="'+encodeURIComponent(JSON.stringify(s))+'"><b>'+esc(s.name)+'</b><span>'+(alphaIntent==="complete"?(en()?"Finish by steps":"단계로 완료하기"):(en()?"Keep in my range":"내 범위로 유지하기"))+'</span><small class="measure-contract">'+esc(contractLabel(s.measure))+'</small><em class="measure-reason">'+esc(s.reason)+'</em></button>').join("");}
function renderClarify(q){const box=$("#entryResults"),title=$("#entryResultTitle");if(!box||!q)return;if(title)title.textContent=en()?"One safe next step":"안전하게 정하는 다음 단계";box.innerHTML='<button class="entry-seed alpha-clarify" data-alpha-clarify="'+encodeURIComponent(q)+'"><b>'+(en()?"Answer 3 simple questions":"쉬운 질문 3개로 정하기")+'</b><span>'+(en()?"What to record · what success means · when to review":"무엇을 기록할지 · 성공 기준 · 확인 주기")+'</span><em class="measure-reason">'+(en()?"If you do not know, start with observation without judgment.":"기준을 모르겠다면 판단 없는 관찰로 시작할 수 있어요.")+'</em></button>';}

function normalizeMeasure(m){m=m&&typeof m==="object"?m:{};if(!m.input)m.input="count";if(!m.aggregation)m.aggregation=m.input==="milestone"?"completion":m.input==="rating"?"average":m.input==="snapshot"?"latest":"sum";if(!m.success)m.success=m.input==="milestone"?"deadline":m.input==="rating"?"none":"at_least";if(!m.period)m.period=m.input==="milestone"?"deadline":"day";if(!m.source)m.source="manual";return m;}
function options(map,value){return Object.keys(map).map(k=>'<option value="'+k+'" '+(k===value?'selected':'')+'>'+map[k]+'</option>').join("");}
function conditionalFields(m){if(m.success==="range")return '<div class="alpha-contract-grid"><label>'+(en()?"Minimum":"최소값")+'<input data-measure="min" type="number" step="any" inputmode="decimal" value="'+(m.min??"")+'"></label><label>'+(en()?"Maximum":"최대값")+'<input data-measure="max" type="number" step="any" inputmode="decimal" value="'+(m.max??"")+'"></label></div>';if(m.input==="rating")return '<div class="alpha-contract-grid"><label>'+(en()?"Scale minimum":"점수 최소")+'<input data-measure="scaleMin" type="number" value="'+(m.scaleMin??1)+'"></label><label>'+(en()?"Scale maximum":"점수 최대")+'<input data-measure="scaleMax" type="number" value="'+(m.scaleMax??5)+'"></label></div>';if(m.input==="milestone"){const lines=(m.milestones||[]).map(x=>x.label||x).join("\n");const date=m.deadlineAt?new Date(m.deadlineAt).toISOString().slice(0,10):"";return '<label>'+(en()?"Steps, one per line":"완료 단계 · 한 줄에 하나")+'<textarea data-measure="milestonesText" rows="3" placeholder="'+(en()?"Research\nBuild\nReview":"조사\n구현\n검토")+'">'+esc(lines)+'</textarea></label><label>'+(en()?"Deadline (optional)":"마감일 (선택)")+'<input data-measure="deadlineDate" type="date" value="'+date+'"></label>';}if(m.success==="at_least"||m.success==="at_most")return '<label>'+(en()?"Target or limit":"목표 또는 한도")+'<input data-measure="target" type="number" step="any" inputmode="decimal" value="'+(m.target??"")+'" placeholder="'+(en()?"Confirm yourself":"직접 확인")+'"></label>';return "";}
function adaptCoreFields(m){const special=m&&(m.input==="rating"||m.input==="milestone"||m.input==="snapshot"||m.success==="range"||m.success==="delta");["#edGoalField","#edCycleField","#edAmountField","#edBaselineField","#edTargetField"].forEach(s=>{const el=$(s);if(el)el.style.display=special?"none":"";});const typeSeg=$("#edTypeSeg");if(typeSeg)typeSeg.style.display=special?"none":"";}
function renderContractEditor(holder,reason){ensureIntentButtons();const purpose=holder&&holder.measure!==undefined?holder:(holder&&holder.purpose?holder.purpose:null);if(!purpose)return;purpose.measure=normalizeMeasure(purpose.measure);currentDraft=purpose.measure;currentReason=reason||purpose.reason||currentReason||"";const m=currentDraft;let box=$("#measureSummary");if(!box){box=document.createElement("div");box.id="measureSummary";box.className="measure-summary";$("#editSheet .sheet-actions").before(box);}const inputs=en()?{count:"Count",amount:"Amount",duration:"Duration",check:"Done / not done",elapsed:"Elapsed",snapshot:"Current value",rating:"Rating",milestone:"Milestone"}:{count:"횟수",amount:"양",duration:"시간",check:"실행 여부",elapsed:"경과",snapshot:"현재값",rating:"점수",milestone:"단계"},aggs=en()?{sum:"Sum",count:"Occurrences",latest:"Latest",average:"Average",rate:"Rate",streak:"Streak",elapsed:"Elapsed",completion:"Completion"}:{sum:"합계",count:"발생 수",latest:"최신값",average:"평균",rate:"비율",streak:"연속",elapsed:"경과",completion:"완료율"},success=en()?{at_least:"At least",at_most:"At most",range:"Inside range",deadline:"By deadline",delta:"Change from start",none:"No judgment"}:{at_least:"이상",at_most:"이하",range:"범위 안",deadline:"마감일까지",delta:"시작보다 변화",none:"판단하지 않음"},periods=en()?{event:"Each time",day:"Daily",week:"Weekly",month:"Monthly",rolling:"Rolling window",total:"All time",deadline:"Deadline"}:{event:"매회",day:"하루",week:"주",month:"월",rolling:"최근 기간",total:"전체",deadline:"마감일"};box.innerHTML='<b>'+(en()?"Confirm measurement":"측정 계약 확인")+'</b><span class="alpha-contract-live">'+esc(contractLabel(m))+'</span><p>'+esc(currentReason||(en()?"You can change every recommendation.":"추천은 언제든 바꿀 수 있어요."))+'</p><div class="alpha-contract-grid"><label>'+(en()?"1. What to record":"1. 무엇을 기록하나요?")+'<select data-measure="input">'+options(inputs,m.input)+'</select></label><label>'+(en()?"2. How to combine":"2. 어떻게 합치나요?")+'<select data-measure="aggregation">'+options(aggs,m.aggregation)+'</select></label><label>'+(en()?"3. What counts as success":"3. 잘된 기준은?")+'<select data-measure="success">'+options(success,m.success)+'</select></label><label>'+(en()?"When to review":"언제 묶어 볼까요?")+'<select data-measure="period">'+options(periods,m.period)+'</select></label></div>'+conditionalFields(m)+'<label>'+(en()?"Unit":"단위")+'<input data-measure="unit" type="text" maxlength="12" value="'+esc(m.unit||"")+'" placeholder="'+(en()?"kg, hours, points":"kg, 시간, 점")+'"></label><div class="alpha-honesty">'+(en()?"Empty criteria stay empty. OmniCounter does not invent medical or financial targets.":"비어 있는 기준은 0으로 만들지 않아요. 의료·재무 기준도 임의로 만들지 않습니다.")+'</div>';adaptCoreFields(m);}
function readControl(el){const k=el.dataset.measure;if(!k||!currentDraft)return;if(k==="milestonesText"){currentDraft.milestones=el.value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean).map((label,i)=>({id:"m"+(i+1),label}));return;}if(k==="deadlineDate"){currentDraft.deadlineAt=el.value?new Date(el.value+"T00:00:00").getTime():null;return;}if(["min","max","target","scaleMin","scaleMax"].includes(k)){currentDraft[k]=el.value===""?null:Number(el.value);return;}currentDraft[k]=el.value;if(k==="input"){const defaults={snapshot:["latest","delta"],rating:["average","none"],milestone:["completion","deadline"],check:["rate","at_least"],elapsed:["elapsed","none"]};if(defaults[el.value]){currentDraft.aggregation=defaults[el.value][0];currentDraft.success=defaults[el.value][1];}if(el.value==="milestone")currentDraft.period="deadline";}if(k==="success"&&el.value==="range"&&!currentDraft.aggregation)currentDraft.aggregation="average";}
function validateDraft(){const m=currentDraft;if(!m)return true;if(m.success==="range"&&(!Number.isFinite(Number(m.min))||!Number.isFinite(Number(m.max))||Number(m.min)>=Number(m.max))){C.showSnack(en()?"Enter a minimum lower than the maximum":"최소값은 최대값보다 작게 입력해 주세요");return false;}if(m.input==="rating"&&Number(m.scaleMin)>=Number(m.scaleMax)){C.showSnack(en()?"Check the rating scale":"점수 범위를 확인해 주세요");return false;}if(m.input==="milestone"&&!(m.milestones||[]).length){C.showSnack(en()?"Add at least one step":"완료 단계를 하나 이상 적어 주세요");return false;}const unit=$("#edUnit");if(unit&&m.unit)unit.value=m.unit;const goal=$("#edGoal");if(goal&&Number.isFinite(Number(m.target)))goal.value=m.target;return true;}

const prevComposer=C.openComposer.bind(C);
C.openComposer=seed=>{seed=seed||{};seed.measure=normalizeMeasure(seed.measure);prevComposer(seed);renderContractEditor({measure:seed.measure,reason:seed.reason},seed.reason);const bridge=window.__OMNI_ALPHA_EDIT;if(bridge&&bridge.setPurpose)bridge.setPurpose({area:seed.area||null,intent:seed.intent||"increase",measure:seed.measure,reason:seed.reason||""});};

function measureOf(c){return c&&c.purpose&&c.purpose.measure||null;}
function isValueMode(c){const m=measureOf(c)||{};return m.input==="snapshot"||m.input==="rating"||m.success==="range"||m.success==="delta";}
function isMilestone(c){const m=measureOf(c)||{};return m.input==="milestone"||m.aggregation==="completion";}
function valueRows(c){return (c.events||[]).filter(e=>Number.isFinite(Number(e.value))).sort((a,b)=>a.t-b.t);}
function valueStats(c){const m=measureOf(c)||{},rows=valueRows(c),vals=rows.map(e=>Number(e.value)),latest=vals.length?vals[vals.length-1]:null,first=vals.length?vals[0]:null,avg=vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null,inside=vals.filter(v=>Number.isFinite(Number(m.min))&&Number.isFinite(Number(m.max))&&v>=Number(m.min)&&v<=Number(m.max)).length;return {rows,latest,first,avg,delta:latest!=null&&first!=null?latest-first:null,inside,total:vals.length,rate:vals.length?inside/vals.length*100:null};}
function pretty(v){if(v==null||!Number.isFinite(Number(v)))return "—";return Number.isInteger(Number(v))?String(Number(v)):String(Math.round(Number(v)*100)/100);}
function valuePrimary(c){const m=measureOf(c)||{},s=valueStats(c);if(m.aggregation==="average")return s.avg;if(m.aggregation==="rate")return s.rate;return s.latest;}
function valueLine(c){const m=measureOf(c)||{},s=valueStats(c);if(!s.total)return en()?"No records yet":"아직 기록이 없어요";if(m.success==="range")return (en()?"In range ":"범위 안 ")+s.inside+"/"+s.total+" · "+Math.round(s.rate)+"%";if(m.success==="delta")return (en()?"Change ":"시작 대비 ")+(s.delta>=0?"+":"")+pretty(s.delta);if(m.aggregation==="average")return (en()?"Average ":"평균 ")+pretty(s.avg)+" · "+s.total+(en()?" records":"개 기록");return en()?"Latest value · never summed":"최신값 · 합산하지 않음";}
let recordCounter=null;
function ensureRecordSheet(){let sh=$("#alphaRecordSheet");if(sh)return sh;sh=document.createElement("div");sh.id="alphaRecordSheet";sh.className="snapshot-sheet";sh.innerHTML='<div class="snapshot-box" role="dialog" aria-modal="true" aria-labelledby="alphaRecordTitle"><b id="alphaRecordTitle"></b><div class="entry-sub" id="alphaRecordHelp"></div><div id="alphaRatingButtons"></div><input id="alphaRecordValue" type="number" inputmode="decimal" step="any"><div class="snapshot-actions"><button id="alphaRecordCancel">'+(en()?"Cancel":"취소")+'</button><button id="alphaRecordSave" class="primary">'+(en()?"Save value":"값 저장")+'</button></div></div>';document.body.appendChild(sh);$("#alphaRecordCancel").onclick=()=>sh.classList.remove("on");sh.addEventListener("click",e=>{if(e.target===sh)sh.classList.remove("on");});$("#alphaRatingButtons").onclick=e=>{const b=e.target.closest("button");if(b)$("#alphaRecordValue").value=b.dataset.rating;};$("#alphaRecordSave").onclick=()=>{if(!recordCounter)return;const v=Number($("#alphaRecordValue").value),m=measureOf(recordCounter)||{};if(!Number.isFinite(v)){C.showSnack(en()?"Enter a number":"숫자를 입력해 주세요");return;}if(m.input==="rating"&&((Number.isFinite(Number(m.scaleMin))&&v<Number(m.scaleMin))||(Number.isFinite(Number(m.scaleMax))&&v>Number(m.scaleMax)))){C.showSnack(en()?"Use a value inside the rating scale":"점수 범위 안의 값을 입력해 주세요");return;}recordCounter.events.push({value:v,t:Date.now(),eventKind:m.input==="rating"?"rating":"value",snapshot:m.input==="snapshot"});C.save();sh.classList.remove("on");C.renderDash();if(C.current==="single"&&C.activeId===recordCounter.id)renderSpecialSingle(recordCounter);};return sh;}
function openValueRecorder(c){recordCounter=c;const sh=ensureRecordSheet(),m=measureOf(c)||{},s=valueStats(c),unit=m.unit||c.baseUnit||"";$("#alphaRecordTitle").textContent=(en()?"Record · ":"기록 · ")+c.name;$("#alphaRecordHelp").textContent=(m.input==="rating"?(en()?"Choose a score in your scale.":"정한 범위 안에서 점수를 골라 주세요."):(en()?"Values stay separate and are never added.":"값은 각각 보존하며 서로 더하지 않아요."))+(unit?" ("+unit+")":"");$("#alphaRecordValue").value=s.latest??"";const ratings=$("#alphaRatingButtons");if(m.input==="rating"){const lo=Number(m.scaleMin)||1,hi=Number(m.scaleMax)||5;ratings.innerHTML=Array.from({length:Math.min(10,hi-lo+1)},(_,i)=>'<button type="button" data-rating="'+(lo+i)+'">'+(lo+i)+'</button>').join("");ratings.style.display="grid";ratings.style.gridTemplateColumns="repeat("+Math.min(5,hi-lo+1)+",1fr)";}else ratings.style.display="none";sh.classList.add("on");setTimeout(()=>$("#alphaRecordValue").focus(),0);}
function milestoneState(c){const m=measureOf(c)||{},steps=(m.milestones||[]).map((x,i)=>typeof x==="string"?{id:"m"+(i+1),label:x}:x),state={};(c.events||[]).filter(e=>e.eventKind==="milestone").sort((a,b)=>a.t-b.t).forEach(e=>state[e.milestoneId]=!!e.done);const done=steps.filter(x=>state[x.id]).length;return {steps,state,done,total:steps.length,pct:steps.length?Math.round(done/steps.length*100):0};}
function deadlineLine(m){if(!m.deadlineAt)return en()?"No deadline":"마감일 없음";const d=Math.ceil((Number(m.deadlineAt)-Date.now())/864e5);return d>=0?(d===0?(en()?"Due today":"오늘 마감"):(en()?d+" days left":"D-"+d)):(en()?Math.abs(d)+" days past":"마감 "+Math.abs(d)+"일 지남");}
function ensurePanel(){let p=$("#uxModePanel");if(!p){p=document.createElement("div");p.id="uxModePanel";$("#sStage").appendChild(p);}return p;}
function renderSpecialSingle(c){if(!isValueMode(c)&&!isMilestone(c))return false;$("#sStage").classList.add("ux-mode");const p=ensurePanel(),count=$("#sCount"),fill=$("#sGoalFill"),txt=$("#sGoalTxt"),hint=$("#sHint"),freeze=$("#sFreeze"),m=measureOf(c)||{};$("#sName").textContent=c.name;$("#sGoalRow").classList.add("on");$("#sGoalRow").classList.remove("hr");$("#sTagRow").classList.remove("on");count.style.color=c.color;if(isMilestone(c)){const st=milestoneState(c);count.textContent=st.pct+"%";fill.style.width=st.pct+"%";fill.style.background=c.color;txt.textContent=st.done+" / "+st.total+" · "+deadlineLine(m);p.innerHTML='<div class="alpha-step-list">'+(st.steps.length?st.steps.map(x=>'<button data-alpha-step="'+esc(x.id)+'" class="'+(st.state[x.id]?'done':'')+'"><span>'+(st.state[x.id]?'✓':'○')+'</span><b>'+esc(x.label)+'</b></button>').join(""):'<div class="ux-honesty">'+(en()?"Add steps in settings":"설정에서 완료 단계를 추가해 주세요")+'</div>')+'</div>';hint.textContent=en()?"Tap a step to complete or undo it":"단계를 눌러 완료하거나 되돌리세요";freeze.textContent=deadlineLine(m);}else{const s=valueStats(c),primary=valuePrimary(c),unit=m.unit||c.baseUnit||"",rows=s.rows.slice(-5).reverse();count.textContent=pretty(primary)+(primary!=null&&unit?" "+unit:"");fill.style.width=m.success==="range"&&s.rate!=null?Math.round(s.rate)+"%":"0%";fill.style.background=c.color;txt.textContent=valueLine(c);p.innerHTML='<button class="ux-timer" data-alpha-record>'+(m.input==="rating"?(en()?"Record rating":"점수 기록"):(en()?"Record value":"값 기록"))+'</button><div class="snapshot-list">'+(rows.length?rows.map(e=>'<div class="snapshot-row"><b>'+esc(pretty(e.value)+(unit?" "+unit:""))+'</b><span>'+new Date(e.t).toLocaleDateString()+'</span></div>').join(""):'<div class="ux-honesty">'+(en()?"No records yet":"아직 기록이 없어요")+'</div>')+'</div>';hint.textContent=en()?"Recorded values remain separate; the contract decides the summary":"기록값은 따로 보존하고 계약에 따라 요약해요";freeze.textContent=(c.purpose&&c.purpose.reason)||"";}hint.classList.add("on");$("#sStage").setAttribute("aria-label",c.name+", "+count.textContent+". "+hint.textContent);return true;}
function renderSpecialCard(c,card,col){if(!isValueMode(c)&&!isMilestone(c))return false;let name,value,line,action,op,icon;if(isMilestone(c)){const st=milestoneState(c);name=en()?"Completion":"완료";value=st.pct+"%";line=st.done+" / "+st.total+" · "+deadlineLine(measureOf(c)||{});action=en()?"View steps":"단계 보기";op="alpha-open";icon="◇";}else{const m=measureOf(c)||{},v=valuePrimary(c);name=m.input==="rating"?(en()?"Rating":"점수"):(en()?"Measured value":"측정값");value=pretty(v);line=valueLine(c)+(m.unit?" · "+m.unit:"");action=m.input==="rating"?(en()?"Record rating":"점수 기록"):(en()?"Record value":"값 기록");op="alpha-record";icon=m.input==="rating"?"★":"↕";}card.innerHTML='<div class="tapzone" role="button" tabindex="0" aria-label="'+esc(c.name)+'" data-id="'+c.id+'"></div><div class="cname">'+icon+' '+esc(c.name)+' · '+name+'</div><div class="cval num" style="color:'+col+';font-size:34px">'+esc(value)+'</div><div class="cgoal">'+esc(line)+'</div><div class="ops"><button class="op plus" data-id="'+c.id+'" data-op="'+op+'" style="background:'+col+';border-color:'+col+'">'+action+'</button></div>';return true;}

const oldOpen=UX.openSingle,oldRender=UX.renderSingle,oldActivate=UX.activate,oldCard=UX.renderDashCard,oldAction=UX.dashboardAction;
UX.openSingle=c=>{if(isValueMode(c)||isMilestone(c))return renderSpecialSingle(c);return oldOpen(c);};
UX.renderSingle=c=>{if(isValueMode(c)||isMilestone(c))return renderSpecialSingle(c);return oldRender(c);};
UX.activate=(c,x,y)=>{if(isValueMode(c)){openValueRecorder(c);return true;}if(isMilestone(c))return renderSpecialSingle(c);return oldActivate(c,x,y);};
UX.renderDashCard=(c,card,col)=>renderSpecialCard(c,card,col)||oldCard(c,card,col);
UX.dashboardAction=(c,op)=>{if(op==="alpha-record"){openValueRecorder(c);return true;}if(op==="alpha-open"){C.openSingle(c.id);return true;}return oldAction(c,op);};
UX.valueStats=valueStats;UX.milestoneState=milestoneState;UX.alphaIntents=Object.keys(INTENTS);

document.addEventListener("click",e=>{
const ai=e.target.closest("[data-alpha-intent]");if(ai){e.preventDefault();e.stopImmediatePropagation();alphaIntent=ai.dataset.alphaIntent;renderAlphaResults();return;}
const aa=e.target.closest("#entryAreas [data-area]");if(aa&&alphaIntent){e.preventDefault();e.stopImmediatePropagation();alphaArea=aa.dataset.area;renderAlphaResults();return;}
const seed=e.target.closest("[data-alpha-seed]");if(seed){e.preventDefault();e.stopImmediatePropagation();C.openComposer(JSON.parse(decodeURIComponent(seed.dataset.alphaSeed)));return;}
const clarify=e.target.closest("[data-alpha-clarify]");if(clarify){e.preventDefault();e.stopImmediatePropagation();const q=decodeURIComponent(clarify.dataset.alphaClarify);C.openComposer({name:q,intent:"notice",type:"aware",measure:{input:"rating",aggregation:"average",success:"none",period:"day",source:"manual",unit:"점",scaleMin:1,scaleMax:5},reason:en()?"Start by observing without judgment; change the contract when your criterion becomes clear.":"기준이 선명해질 때까지 판단 없이 관찰하고 언제든 계약을 바꿀 수 있어요."});return;}
const ei=e.target.closest("[data-alpha-edit-intent]");if(ei){e.preventDefault();e.stopImmediatePropagation();const v=ei.dataset.alphaEditIntent,b=window.__OMNI_ALPHA_EDIT;if(b&&b.setIntent)b.setIntent(v);$$("#edIntentSeg button").forEach(x=>x.classList.toggle("on",x===ei));return;}
const rec=e.target.closest("[data-alpha-record]");if(rec){e.preventDefault();e.stopPropagation();const c=C.byId(C.activeId);if(c)openValueRecorder(c);return;}
const step=e.target.closest("[data-alpha-step]");if(step){e.preventDefault();e.stopPropagation();const c=C.byId(C.activeId);if(!c)return;const st=milestoneState(c),done=!st.state[step.dataset.alphaStep];c.events.push({t:Date.now(),eventKind:"milestone",milestoneId:step.dataset.alphaStep,done});C.save();C.renderDash();renderSpecialSingle(c);return;}
if(e.target.closest("#sEdit"))setTimeout(()=>{const b=window.__OMNI_ALPHA_EDIT,p=b&&b.getPurpose&&b.getPurpose();if(p)renderContractEditor(p,p.reason);},0);
if(e.target.closest("#sStat"))setTimeout(()=>{const c=C.byId(C.activeId);if(!c||(!isValueMode(c)&&!isMilestone(c)))return;if(isMilestone(c)){const st=milestoneState(c);$("#statTotal").textContent=st.pct+"%";$("#statSubtitle").textContent=(en()?"Completed steps · ":"완료 단계 · ")+st.done+"/"+st.total;}else{$("#statTotal").textContent=pretty(valuePrimary(c))+((measureOf(c)||{}).unit?" "+measureOf(c).unit:"");$("#statSubtitle").textContent=valueLine(c);}},0);
},true);
document.addEventListener("input",e=>{if(e.target.matches("#measureSummary [data-measure]")){readControl(e.target);if(e.target.tagName==="SELECT")renderContractEditor({measure:currentDraft,reason:currentReason},currentReason);else{const live=$(".alpha-contract-live");if(live)live.textContent=contractLabel(currentDraft);}return;}if(e.target.id==="entrySearch"){alphaIntent=null;const q=e.target.value.trim();if(q&&!["체중","수면","약","회의","저축","예산","빚","프로젝트","기분","운동","혈압","금연","술","카페인","스크린타임"].some(k=>q.includes(k)))setTimeout(()=>renderClarify(q),0);}},true);
document.addEventListener("change",e=>{if(e.target.matches("#measureSummary [data-measure]")){readControl(e.target);if(e.target.tagName==="SELECT"){renderContractEditor({measure:currentDraft,reason:currentReason},currentReason);const cyc=$("#edCycleSeg [data-cycle='"+currentDraft.period+"']");if(cyc)cyc.click();}}},true);
$("#edSave")?.addEventListener("click",e=>{if(!validateDraft()){e.preventDefault();e.stopImmediatePropagation();}},true);
const style=document.createElement("style");style.textContent=`#dashScroll{overflow-x:hidden}#entryIntents{flex-wrap:wrap;overflow:visible}#entryIntents button{flex:1 0 28%;padding:0 9px}.alpha-contract-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:10px}.measure-summary label{display:block;color:var(--ink-dim);font-size:10px;font-weight:750;margin-top:9px}.measure-summary select,.measure-summary input,.measure-summary textarea{display:block;width:100%;min-height:42px;margin-top:5px;border:1px solid var(--line);border-radius:10px;background:var(--bg);color:var(--ink);padding:8px;font:inherit}.measure-summary textarea{min-height:78px;resize:vertical}.alpha-honesty{font-size:10px;line-height:1.45;color:var(--ink-dim);margin-top:10px}.alpha-step-list{width:min(340px,94%);display:grid;gap:8px}.alpha-step-list button{display:flex;align-items:center;gap:10px;min-height:48px;text-align:left;border:1px solid var(--line);border-radius:13px;background:var(--card);color:var(--ink);padding:9px 12px}.alpha-step-list button.done{border-color:var(--accent);color:var(--accent)}#alphaRatingButtons{gap:7px;margin-top:12px}#alphaRatingButtons button{min-height:44px;border:1px solid var(--line);border-radius:11px;background:var(--card);color:var(--ink);font-weight:800}@media(max-width:350px){#entryIntents button{flex-basis:44%}.alpha-contract-grid{grid-template-columns:1fr}}`;
document.head.appendChild(style);
ensureIntentButtons();
const mo=new MutationObserver(()=>ensureIntentButtons());mo.observe(document.documentElement,{attributes:true,attributeFilter:["lang"]});
document.documentElement.dataset.omniAlpha="v24.1-alpha.1";
if(C.current==="dash")C.renderDash();
else if(C.current==="single"&&C.activeId){const active=C.byId(C.activeId);if(active)C.openSingle(active.id);}
})();
